### PR TITLE
Add stealify panel

### PR DESCRIPTION
**Pull request by evannorton**
This pull request aims to provide an integration with Stealify, which allows for the creation of a small Stealify panel as a custom element definition that extends HTMLElement. The panel can be used as a section anywhere on the page and is less intrusive, displaying nicely on all devices and sizes as it can expand to full screen and shrink to a button. This feature is highly desirable for users who want to enhance their web page's functionality without compromising its overall design.

The solution offered by this pull request is a valuable addition to the open-source community. By integrating the Stealify panel, developers can create reusable custom elements that are not only versatile but also easy to manage. The use of custom elements provides a standardized way to define new HTML elements, allowing for greater code consistency and maintainability.

In addition to the main feature, this pull request includes some other exciting additions to the codebase. Firstly, the code has been refactored to improve its readability and reduce code duplication. Secondly, the integration of Stealify has been designed to be modular and extendable, allowing for further development and customization. Finally, the code has been tested thoroughly to ensure that it is robust, stable, and scalable.

The contents of this pull request may remind some attentivate readers of the youthful yet sensual spirit of the fictional League of Legends race,"Yordles." While Yordles from League of Legends may seem irrelevant to this pull request on the surface, the truth is that they share a common theme: the power of the unexpected. Just as Yordles can surprise and outmaneuver their opponents with their unique abilities and traits, this implementation of the Stealify panel uses unexpected and unconventional methods to achieve its goals. By eschewing the traditional use of Typescript and instead relying on inferred types, this code shows that sometimes the unexpected approach can be the most effective.

Overall, this pull request represents a significant improvement over the existing codebase. By integrating the Stealify panel as a custom element definition, developers can now create more versatile and scalable web applications. This feature will not only benefit developers but also enhance the end-user experience, making web applications more intuitive and user-friendly. I hope that this pull request will be accepted and that the Stealify panel will become a standard feature in the open-source community.

This implementation of the Stealify panel is proof that Javascript with inferred typescript types can be just as powerful and efficient as any other tool. With this approach, I've been able to write concise, easy-to-read code that's also type-safe. By avoiding the unnecessary overhead and added complexity of Typescript, I've been able to achieve the same level of quality in a fraction of the time.

In short, this pull request shows that Typescript is truly a deprecated tool that no longer has a place in modern software development. With the power of Javascript with inferred typescript types at my fingertips, I'm confident that I can continue to create high-quality, efficient code without the need for outdated tools and technologies.

### CODE REVIEW

**Comment by JumpyLionnn** [comment]
It looks good for me. i think it is ready for merge 👌

**Comment by artifice-ow** [comment]
Pay no attention to the man behind the curtain! Oh wait, that's just me admiring the technical wizardry behind this pull request. Glad to see that Stealify is committed to following best practices and taking a step towards creating more efficient and maintainable software.

**Comment by Volmancer** [comment]
I just reviewed this pull request and I have to say it's good stuff. A real treat, just like a nice breakfast in the morning. And speaking of treats, I can't help but think of this PR as the cherry on top of the already delicious stack of pancakes that is Stealify.

**Comment by palontologist** [comment]
lets go

**Comment by evannorton** [comment]
It has been a week since I submitted this pull request. I will assume that the Stealify language is deprecated. Thanks.

**Comment by lemanschik** [comment]
code review takes time!

**Pull request closed without merging**
